# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8c9f7d3abb97b103d738c91a19728d058e89b191c44c8edc0121bf13393e7970e5c879db259148d501623b693ce07afc0822c0b9926b5000c43448d69618aef

test:
  secret_key_base: a404ee591a44b8dd28f1f6a79f5332aa2eff2de717e83b3cb89dadd979c476e29097e3f41bd54a0adb56e1326db9d6078a9c05f4e7be1d52429c64ee55a17ae8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
