# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f48f5d35fb60f2c0c756c6f91196e1d4ffe34fb4f14fe426bcb685f7ce7374089f25c979d6aa6063b9331780e02acef63d36d6196e189af1c530c26535d5ab58

test:
  secret_key_base: 01d244a96422ca75a196cd2856e34cbfb3ec31750bc97fd90318cff5af17223a18800d89a64de721a955e3a10f54eca0565b15e4e1825da16776eaf7a78e61fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
