---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 42779444-sgJ10qIMPrirhHwdEesJWkJjtlOpCPnWvOpLEJ0kg
:access_token_secret: VjJ9D9QOl1e8MW56UifO7mlDGXSzNS6ooUhfcpvPx7TsS
